# Generated by Django 6.0.3 on 2026-04-02 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leads",
            name="score",
        ),
    ]
